-- Seed souvera_entities from coverage manifests (74 active markets)
-- Run after create-souvera-entities.sql

INSERT INTO public.souvera_entities (entity_key, name, iso2, iso3, region, entity_type, coverage_status, notes)
VALUES
  ('USA', 'United States', 'US', 'USA', 'caribbean', 'sovereign', 'excluded', 'Sovereign parent reference only'),
  ('GBR', 'United Kingdom', 'GB', 'GBR', 'caribbean', 'sovereign', 'excluded', 'Sovereign parent reference only')
ON CONFLICT (entity_key) DO NOTHING;

INSERT INTO public.souvera_entities (entity_key, name, iso2, iso3, region, entity_type, sovereign_parent_entity_key, coverage_status, notes)
VALUES
  ('MAR', 'Morocco', 'MA', 'MAR', 'africa', 'sovereign', NULL, 'active', 'AGOA not_applicable'),
  ('DZA', 'Algeria', 'DZ', 'DZA', 'africa', 'sovereign', NULL, 'active', 'AGOA not_applicable'),
  ('TUN', 'Tunisia', 'TN', 'TUN', 'africa', 'sovereign', NULL, 'active', 'AGOA not_applicable'),
  ('LBY', 'Libya', 'LY', 'LBY', 'africa', 'sovereign', NULL, 'active', 'AGOA not_applicable'),
  ('EGY', 'Egypt', 'EG', 'EGY', 'africa', 'sovereign', NULL, 'active', 'AGOA not_applicable'),
  ('SDN', 'Sudan', 'SD', 'SDN', 'africa', 'sovereign', NULL, 'active', NULL),
  ('NGA', 'Nigeria', 'NG', 'NGA', 'africa', 'sovereign', NULL, 'active', 'Full terminal pilot; ECOWAS'),
  ('GHA', 'Ghana', 'GH', 'GHA', 'africa', 'sovereign', NULL, 'active', 'ECOWAS'),
  ('SEN', 'Senegal', 'SN', 'SEN', 'africa', 'sovereign', NULL, 'active', 'ECOWAS'),
  ('MLI', 'Mali', 'ML', 'MLI', 'africa', 'sovereign', NULL, 'active', 'ECOWAS'),
  ('BFA', 'Burkina Faso', 'BF', 'BFA', 'africa', 'sovereign', NULL, 'active', 'ECOWAS'),
  ('NER', 'Niger', 'NE', 'NER', 'africa', 'sovereign', NULL, 'active', 'ECOWAS'),
  ('GIN', 'Guinea', 'GN', 'GIN', 'africa', 'sovereign', NULL, 'active', 'ECOWAS'),
  ('SLE', 'Sierra Leone', 'SL', 'SLE', 'africa', 'sovereign', NULL, 'active', 'ECOWAS'),
  ('LBR', 'Liberia', 'LR', 'LBR', 'africa', 'sovereign', NULL, 'active', 'ECOWAS'),
  ('CIV', 'Ivory Coast', 'CI', 'CIV', 'africa', 'sovereign', NULL, 'active', 'ECOWAS'),
  ('TGO', 'Togo', 'TG', 'TGO', 'africa', 'sovereign', NULL, 'active', 'ECOWAS'),
  ('BEN', 'Benin', 'BJ', 'BEN', 'africa', 'sovereign', NULL, 'active', 'ECOWAS'),
  ('GMB', 'Gambia', 'GM', 'GMB', 'africa', 'sovereign', NULL, 'active', 'ECOWAS'),
  ('GNB', 'Guinea-Bissau', 'GW', 'GNB', 'africa', 'sovereign', NULL, 'active', 'ECOWAS'),
  ('CPV', 'Cape Verde', 'CV', 'CPV', 'africa', 'sovereign', NULL, 'active', 'ECOWAS'),
  ('MRT', 'Mauritania', 'MR', 'MRT', 'africa', 'sovereign', NULL, 'active', 'ECOWAS'),
  ('ETH', 'Ethiopia', 'ET', 'ETH', 'africa', 'sovereign', NULL, 'active', NULL),
  ('KEN', 'Kenya', 'KE', 'KEN', 'africa', 'sovereign', NULL, 'active', 'Full terminal pilot'),
  ('TZA', 'Tanzania', 'TZ', 'TZA', 'africa', 'sovereign', NULL, 'active', NULL),
  ('UGA', 'Uganda', 'UG', 'UGA', 'africa', 'sovereign', NULL, 'active', NULL),
  ('RWA', 'Rwanda', 'RW', 'RWA', 'africa', 'sovereign', NULL, 'active', NULL),
  ('BDI', 'Burundi', 'BI', 'BDI', 'africa', 'sovereign', NULL, 'active', NULL),
  ('SOM', 'Somalia', 'SO', 'SOM', 'africa', 'sovereign', NULL, 'active', NULL),
  ('DJI', 'Djibouti', 'DJ', 'DJI', 'africa', 'sovereign', NULL, 'active', NULL),
  ('ERI', 'Eritrea', 'ER', 'ERI', 'africa', 'sovereign', NULL, 'active', NULL),
  ('MDG', 'Madagascar', 'MG', 'MDG', 'africa', 'sovereign', NULL, 'active', NULL),
  ('COM', 'Comoros', 'KM', 'COM', 'africa', 'sovereign', NULL, 'active', NULL),
  ('MUS', 'Mauritius', 'MU', 'MUS', 'africa', 'sovereign', NULL, 'active', NULL),
  ('SYC', 'Seychelles', 'SC', 'SYC', 'africa', 'sovereign', NULL, 'active', NULL),
  ('SSD', 'South Sudan', 'SS', 'SSD', 'africa', 'sovereign', NULL, 'active', NULL),
  ('CMR', 'Cameroon', 'CM', 'CMR', 'africa', 'sovereign', NULL, 'active', NULL),
  ('CAF', 'Central African Republic', 'CF', 'CAF', 'africa', 'sovereign', NULL, 'active', NULL),
  ('COD', 'DR Congo', 'CD', 'COD', 'africa', 'sovereign', NULL, 'active', NULL),
  ('COG', 'Republic of Congo', 'CG', 'COG', 'africa', 'sovereign', NULL, 'active', NULL),
  ('GAB', 'Gabon', 'GA', 'GAB', 'africa', 'sovereign', NULL, 'active', NULL),
  ('GNQ', 'Equatorial Guinea', 'GQ', 'GNQ', 'africa', 'sovereign', NULL, 'active', NULL),
  ('STP', 'São Tomé and Príncipe', 'ST', 'STP', 'africa', 'sovereign', NULL, 'active', NULL),
  ('TCD', 'Chad', 'TD', 'TCD', 'africa', 'sovereign', NULL, 'active', NULL),
  ('AGO', 'Angola', 'AO', 'AGO', 'africa', 'sovereign', NULL, 'active', NULL),
  ('ZAF', 'South Africa', 'ZA', 'ZAF', 'africa', 'sovereign', NULL, 'active', NULL),
  ('BWA', 'Botswana', 'BW', 'BWA', 'africa', 'sovereign', NULL, 'active', NULL),
  ('LSO', 'Lesotho', 'LS', 'LSO', 'africa', 'sovereign', NULL, 'active', NULL),
  ('SWZ', 'Eswatini', 'SZ', 'SWZ', 'africa', 'sovereign', NULL, 'active', NULL),
  ('NAM', 'Namibia', 'NA', 'NAM', 'africa', 'sovereign', NULL, 'active', NULL),
  ('ZWE', 'Zimbabwe', 'ZW', 'ZWE', 'africa', 'sovereign', NULL, 'active', NULL),
  ('MOZ', 'Mozambique', 'MZ', 'MOZ', 'africa', 'sovereign', NULL, 'active', NULL),
  ('ZMB', 'Zambia', 'ZM', 'ZMB', 'africa', 'sovereign', NULL, 'active', NULL),
  ('MWI', 'Malawi', 'MW', 'MWI', 'africa', 'sovereign', NULL, 'active', NULL),
  ('ATG', 'Antigua and Barbuda', 'AG', 'ATG', 'caribbean', 'sovereign', NULL, 'active', 'CARICOM member scope'),
  ('BHS', 'Bahamas', 'BS', 'BHS', 'caribbean', 'sovereign', NULL, 'active', 'CARICOM member scope'),
  ('BRB', 'Barbados', 'BB', 'BRB', 'caribbean', 'sovereign', NULL, 'active', 'CARICOM member scope'),
  ('CUB', 'Cuba', 'CU', 'CUB', 'caribbean', 'sovereign', NULL, 'active', 'CBI typically not applicable'),
  ('DMA', 'Dominica', 'DM', 'DMA', 'caribbean', 'sovereign', NULL, 'active', 'CARICOM member scope'),
  ('DOM', 'Dominican Republic', 'DO', 'DOM', 'caribbean', 'sovereign', NULL, 'active', 'CARICOM associate candidate'),
  ('GRD', 'Grenada', 'GD', 'GRD', 'caribbean', 'sovereign', NULL, 'active', 'CARICOM member scope'),
  ('HTI', 'Haiti', 'HT', 'HTI', 'caribbean', 'sovereign', NULL, 'active', 'CARICOM member scope'),
  ('JAM', 'Jamaica', 'JM', 'JAM', 'caribbean', 'sovereign', NULL, 'active', 'Full terminal pilot'),
  ('KNA', 'Saint Kitts and Nevis', 'KN', 'KNA', 'caribbean', 'sovereign', NULL, 'active', 'CARICOM member scope'),
  ('LCA', 'Saint Lucia', 'LC', 'LCA', 'caribbean', 'sovereign', NULL, 'active', 'CARICOM member scope'),
  ('VCT', 'Saint Vincent and the Grenadines', 'VC', 'VCT', 'caribbean', 'sovereign', NULL, 'active', 'CARICOM member scope'),
  ('SUR', 'Suriname', 'SR', 'SUR', 'caribbean', 'sovereign', NULL, 'active', 'Caribbean mandate'),
  ('TTO', 'Trinidad and Tobago', 'TT', 'TTO', 'caribbean', 'sovereign', NULL, 'active', 'CARICOM member scope'),
  ('GUY', 'Guyana', 'GY', 'GUY', 'caribbean', 'sovereign', NULL, 'active', 'Caribbean mandate'),
  ('BLZ', 'Belize', 'BZ', 'BLZ', 'caribbean', 'sovereign', NULL, 'active', 'Caribbean mandate'),
  ('PRI', 'Puerto Rico', 'PR', 'PRI', 'caribbean', 'territory', 'USA', 'active', 'US territory; CBI evidence-only'),
  ('VGB', 'British Virgin Islands', 'VG', 'VGB', 'caribbean', 'territory', 'GBR', 'active', 'UK BOT'),
  ('TCA', 'Turks and Caicos Islands', 'TC', 'TCA', 'caribbean', 'territory', 'GBR', 'active', 'UK BOT'),
  ('CYM', 'Cayman Islands', 'KY', 'CYM', 'caribbean', 'territory', 'GBR', 'active', 'UK BOT')
ON CONFLICT (entity_key) DO UPDATE SET
  name = EXCLUDED.name,
  iso2 = EXCLUDED.iso2,
  iso3 = EXCLUDED.iso3,
  region = EXCLUDED.region,
  entity_type = EXCLUDED.entity_type,
  sovereign_parent_entity_key = EXCLUDED.sovereign_parent_entity_key,
  coverage_status = EXCLUDED.coverage_status,
  notes = EXCLUDED.notes;
