/**
 * HTML report templates — rendered to PDF via pdf-lib text layout.
 * Future: migrate to Puppeteer for full HTML/CSS fidelity.
 */

export interface ReportTemplateContext {
  countryName: string;
  iso3: string;
  reportType: string;
  generatedAt: string;
  summary?: string;
  opportunityThesis?: string;
  riskNarrative?: string;
  query?: string;
}

export function buildReportSections(ctx: ReportTemplateContext): { title: string; body: string }[] {
  const sections: { title: string; body: string }[] = [
    {
      title: 'Executive Summary',
      body:
        ctx.summary ??
        `${ctx.countryName} (${ctx.iso3}) intelligence report generated by Souvera. This document synthesizes macro, sector, trade, and risk data for investment decision-making.`,
    },
  ];

  if (ctx.reportType === 'Investment Memo' || ctx.reportType === 'AI Custom Report') {
    sections.push({
      title: 'Investment Thesis',
      body:
        ctx.opportunityThesis ??
        'Investment thesis data will populate from country profile narratives when available.',
    });
    sections.push({
      title: 'Risk Assessment',
      body:
        ctx.riskNarrative ??
        'Risk narrative data will populate from country profile when available.',
    });
  }

  if (ctx.reportType === 'Trade Profile') {
    sections.push({
      title: 'U.S. Trade Relationship',
      body: `Bilateral trade analysis for ${ctx.countryName}. See Trade tab for live figures including market access programs and export opportunities.`,
    });
  }

  if (ctx.reportType === 'Sector Deep-Dive') {
    sections.push({
      title: 'Sector Analysis',
      body:
        'Sector Deep-Dive v2 was not used for this request. Regenerate with sectorKey to receive the institutional Puppeteer report.',
    });
  }

  if (ctx.reportType === 'AI Custom Report' && ctx.query) {
    sections.unshift({
      title: 'Custom Query',
      body: ctx.query,
    });
  }

  sections.push({
    title: 'Disclaimer',
    body:
      'This report is for informational purposes only and does not constitute investment advice. Data sourced from World Bank, UN Comtrade, and Souvera analysis. © Souvera Intelligence.',
  });

  return sections;
}
